#!/bin/bash

#########################################################
#
# Platform: NCI Gadi HPC
# Description: Runs gatk4_hc_gathervcfs.sh in parallel
# Usage: Adjust <project> and compute resource requests following the guide
# below, then qsub gatk4_hc_gathervcfs_run_parallel.pbs
# Job resource requirements:
# ~18Gb memory per normal sample in ../<cohort>.config
# Using normalbw queue, request 28 CPU, 256Gb mem per 24-34 samples, 
# setting NCPUS=2 allows ~18Gb memory per sample
# Benchmarking metrics: For 60 human samples, ~35X
# Requested: walltime=02:00:00,ncpus=56,mem=512GB,wd normalbw
# Used: walltime=01:39:38,ncpus=56,mem=461.91GB, SUs=118.08
# Author: Tracy Chew
# tracy.chew@sydney.edu.au
# Date last modified: 17/08/2020
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

#PBS -P <project>
#PBS -N hc_gathervcfs
#PBS -l walltime=02:00:00,ncpus=96,mem=384GB,wd
#PBS -q normalbw
#PBS -W umask=022
#PBS -l storage=scratch/<project>
#PBS -o ./Logs/gatk4_hc_gathervcfs.o
#PBS -e ./Logs/gatk4_hc_gathervcfs.e
#PBS -m ae

# NCPUs = CPUs per task
NCPUS=2
		
#########################################################
# Do not edit below this line (unless running on a node that
# does not have 48 CPU, in which case edit the value of 'CPN'
#########################################################

module load openmpi/4.0.2
module load nci-parallel/1.0.0

set -e
			
# SCRIPT
SCRIPT=./gatk4_hc_gathervcfs.sh
INPUTS=./Inputs/gatk4_hc_gathervcfs.inputs

echo "$(date) : GATK 4 GatherVcfs."

CPN=48 #CPUs per node 
M=$(( CPN / NCPUS )) #tasks per node

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / CPN)) \
        --map-by node:PE=${NCPUS} \
        nci-parallel \
        --verbose \
        --input-file ${PBS_JOBFS}/input-file
