#!/bin/bash

#########################################################
#
# Platform: NCI Gadi HPC
# Description: Runs gatk4_hc.sh in parallel, which calls variants
# for a pre defined genomic-interval using inputs created from
# gatk4_hc_make_input.sh
# Usage: Adjust <project> and compute resource requests following the guide
# below, then qsub gatk4_hc_run_parallel.pbs
# Job resource requirements:
# walltime=02:00:00 (job expected to complete in ~1 hour)
# ncpus=48*2*N (N=number of samples in ../<cohort>.config)
# mem=192*2*N GB (N=number of samples in ../<cohort>.config)
# Per task requirements:
# 1 task requires 1 CPU, 4GB mem
# Author: Tracy Chew
# tracy.chew@sydney.edu.au
# Date last modified: 24/02/2021
#
# If you use this script towards a publication, please acknowledge the
# Sydney Informatics Hub (or co-authorship, where appropriate).
#
# Suggested citation:
# Sydney Informatics Hub, Core Research Facilities, University of Sydney,
# 2021, The Sydney Informatics Hub Bioinformatics Repository, <date accessed>,
# https://github.com/Sydney-Informatics-Hub/Bioinformatics
#
# Suggested acknowledgement:
# The authors acknowledge the scientific and technical assistance
# <or e.g. bioinformatics assistance of <PERSON>> of Sydney Informatics
# Hub and resources and services from the National Computational
# Infrastructure (NCI), which is supported by the Australian Government
# with access facilitated by the University of Sydney.
#
#########################################################

#PBS -P er01
#PBS -N hc
#PBS -l walltime=02:00:00,ncpus=3264,mem=12920GB,wd
#PBS -q normal
#PBS -W umask=022
#PBS -l storage=scratch/er01+scratch/hm82
#PBS -o ../Logs/gatk4_hc_0.o
#PBS -e ../Logs/gatk4_hc_0.e

INPUTS=./Inputs/gatk4_hc.inputs
#INPUTS=./Inputs/gatk4_hc_0.inputs

#########################################################
# Do not edit below this line 
#########################################################

module load openmpi/4.0.2
module load nci-parallel/1.0.0
module load gatk/4.1.2.0

set -e

# NCPUs = CPUs per task
NCPUS=1
			
# SCRIPT
SCRIPT=./gatk4_hc.sh

if [[ $PBS_QUEUE =~ bw-exec ]]; then CPN=28; else CPN=48; fi
M=$(( CPN / NCPUS )) #tasks per node

sed "s|^|${SCRIPT} |" ${INPUTS} > ${PBS_JOBFS}/input-file

mpirun --np $((M * PBS_NCPUS / CPN)) \
        --map-by node:PE=${NCPUS} \
        nci-parallel \
        --verbose \
        --input-file ${PBS_JOBFS}/input-file

